/* -------------------------------------------------------------------*
* FileName:        traps.c
* Dependencies:    p33FJ256GP710.h
* Processor:       dsPIC33F
* Compiler:        MPLAB. C30 v2.01 or higher
* ADDITIONAL NOTES:
* 1. This file contains trap service routines (handlers) for hardware
*    exceptions generated by dsPIC30F device.
* 2. All trap service routines in this file simply ensure that device
*    continuously executes code within trap service routine. Users
*    may modify basic framework provided here to suit to needs
*    of their application.
* -------------------------------------------------------------------*/
#include "p33FJ256GP710.h"
#include "timer1.h"

void __attribute__((__interrupt__, no_auto_psv)) _OscillatorFail( void );
void __attribute__((__interrupt__, no_auto_psv)) _AddressError( void );
void __attribute__((__interrupt__, no_auto_psv)) _StackError( void );
void __attribute__((__interrupt__, no_auto_psv)) _MathError( void );
void __attribute__((__interrupt__, no_auto_psv)) _DMACError( void );
void __attribute__((__interrupt__, no_auto_psv)) _AltOscillatorFail( void );
void __attribute__((__interrupt__, no_auto_psv)) _AltAddressError( void );
void __attribute__((__interrupt__, no_auto_psv)) _AltStackError( void );
void __attribute__((__interrupt__, no_auto_psv)) _AltMathError( void );
void __attribute__((__interrupt__, no_auto_psv)) _AltDMACError( void );

/* ------------Primary Exception Vector handlers:-------------------
   These routines are used if INTCON2bits.ALTIVT = 0.
   All trap service routines in this file simply ensure that device
   continuously executes code within trap service routine. Users
   may modify basic framework provided here to suit to needs
   of their application.
 ------------------------------------------------------------------*/
void __attribute__((__interrupt__, no_auto_psv)) _OscillatorFail( void )
{
  INTCON1bits.OSCFAIL = 0;        //Clear trap flag
  while(1);
}

void __attribute__((__interrupt__, no_auto_psv)) _AddressError( void )
{
  INTCON1bits.ADDRERR = 0;        //Clear trap flag
  // while(1);
  Nop();
}

void __attribute__((__interrupt__, no_auto_psv)) _StackError( void )
{
  INTCON1bits.STKERR = 0;         //Clear trap flag
  while(1);
}

void __attribute__((__interrupt__, no_auto_psv)) _MathError( void )
{
//int icon;

//	tft_SetFont( fontTC26PB );
//	tft_SetLoc(  15,  0 );  // centered at toop of screen
//	tft_setBG( TFTWHITE );  
//	tft_setFG( TFTRED );  
//	tft_SetFont( fontTC10x14 );
//	tft_putsCent( "!A Math-Error occured! 0x" );
//	icon = INTCON1;
//	tft_puthex( icon / 0x100 );
//	tft_puthex( icon || 0xFF );
//
//	uiSoakTimr = 10; // 10 sec delay
//	while( uiSoakTimr )
//	{
//		tft_SetLoc(  0,  0 );
//		tft_putint( uiSoakTimr);
//	}
//
//	tft_setFG(TFTCYAN);
//	tft_setBG(TFTBLACK);
//
//	tft_SetLoc(  0,  0 );
//	tft_puts( "   " );

  	INTCON1bits.MATHERR = 0;        //Clear trap flag
//  while(1);
}

void __attribute__((__interrupt__, no_auto_psv)) _DMACError( void )
{
  /* reset status bits, real app should check which ones */
  DMACS0 = 0;

  INTCON1bits.DMACERR = 0;        //Clear trap flag
  while(1);
}

/* -----------Alternate Exception Vector handlers:-------------------
   These routines are used if INTCON2bits.ALTIVT = 1.
   All trap service routines in this file simply ensure that device
   continuously executes code within trap service routine. Users
   may modify basic framework provided here to suit to needs
   of their application.
 ------------------------------------------------------------------*/
void __attribute__((__interrupt__, no_auto_psv)) _AltOscillatorFail( void )
{
  INTCON1bits.OSCFAIL = 0;
  while(1);
}

void __attribute__((__interrupt__, no_auto_psv)) _AltAddressError( void )
{
  INTCON1bits.ADDRERR = 0;
  while(1);
}

void __attribute__((__interrupt__, no_auto_psv)) _AltStackError( void )
{
  INTCON1bits.STKERR = 0;
  while(1);
}

void __attribute__((__interrupt__, no_auto_psv)) _AltMathError( void )
{
  INTCON1bits.MATHERR = 0;
  while(1);
}

void __attribute__((__interrupt__, no_auto_psv)) _AltDMACError( void )
{
  /* reset status bits, real app should check which ones */
  DMACS0 = 0;

  INTCON1bits.DMACERR = 0;        //Clear trap flag i1
  while(1);
}
